name: Security - Check Secret Leaks (.env)

# Define when the Action is triggered
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  verify-no-env-files:
    name: Prevent .env Uploads
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download the code to the github VM repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Look for .env in the repository
      - name: Check for .env files
        run: |
          echo "Search for .env files int the repository"
          
          # Search for any file that begins with .env, intentionally excluding .env.example
          FOUND_FILES=$(find . -type f -name ".env*" ! -name ".env.example" ! -name ".env.local.example" -not -path "*/node_modules/*")

          if [ -n "$FOUND_FILES" ]; then
            echo "::error::.env FILES EXPOSED IN THE REPOSITORY WERE DETECTED:"
            echo "$FOUND_FILES"
            echo "---------------------------------------------------------"
            echo "For security reasons, you should NEVER upload .env files to Git."
            echo "Remove the file from the cache with: git rm --cached <file>"
            exit 1
          else
            echo "✅ Verification passed: No .env files were detected in the commit."
          fi